ktor:
  application:
    modules:
      - com.ltcoe.ApplicationKt.module
  deployment:
    port: 8080

    # Configure database
    database:
      url: ${DB_URL}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
